# Menus
menu:
  home: .
  about: about
  docs: docs/version-master
  pricing: pricing
  news: news

# Customize
customize:
    logo:
        enabled: true
        width: 48
        height: 48
        url: images/logo48.png
    highlight: monokai
    create: true # create your instance sidebar
    sidebar: false # news sidebar
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/gadael/gadael
        twitter: /
        facebook: /
        dribbble: /
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# Share
share: addtoany # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
