# Menus
menu:
    about: about/
    docs: docs/version-master/
    pricing: pricing/
    news: news/

home:
    icons:  # font awesome names, and matches in languages files
        - globe
        - mobile
        - google
        - tasks
        - github
        - database


# Customize
customize:
    logo:
        enabled: true
        width: 48
        height: 48
        url: images/logo48.png
    highlight: monokai
    create: true # create your instance sidebar
    sidebar: false # news sidebar
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/gadael/gadael
        bug: http://github.com/gadael/gadael/issues
        twitter: https://twitter.com/G4dael
        facebook: https://www.facebook.com/g4dael/
        linkedin: https://www.linkedin.com/company/11006685
        google-plus: https://plus.google.com/communities/112621883074710822989
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false


# Widgets
widgets:
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# Share
share: addtoany # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code


# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id: g4dael
        fb_admins:
        twitter_site: "@G4dael"
        twitter_id: "@paulderosanbo"
        google_plus:
        image: https://www.gadael.com/css/images/logo192.png
    links:
        Hexo: http://hexo.io
